// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASa2g3kae3Jezy0wlsC25Ggx66GN-rWws',
    appId: '1:331400873826:web:3cfefc330e66f5db850e3b',
    messagingSenderId: '331400873826',
    projectId: 'ecommerce-app-54d1e',
    authDomain: 'ecommerce-app-54d1e.firebaseapp.com',
    storageBucket: 'ecommerce-app-54d1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0-J_11LhfFtGHInEVBnVNQo5vDn03Lz8',
    appId: '1:331400873826:android:d4652685c206c728850e3b',
    messagingSenderId: '331400873826',
    projectId: 'ecommerce-app-54d1e',
    storageBucket: 'ecommerce-app-54d1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbNsz4BlHqfzsYGnnuQlq1iA4Pna6rjr4',
    appId: '1:331400873826:ios:cedf5fe0175ab919850e3b',
    messagingSenderId: '331400873826',
    projectId: 'ecommerce-app-54d1e',
    storageBucket: 'ecommerce-app-54d1e.firebasestorage.app',
    iosClientId: '331400873826-60c37u1d44338jtiomiv4ls6ep4eglji.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbNsz4BlHqfzsYGnnuQlq1iA4Pna6rjr4',
    appId: '1:331400873826:ios:cedf5fe0175ab919850e3b',
    messagingSenderId: '331400873826',
    projectId: 'ecommerce-app-54d1e',
    storageBucket: 'ecommerce-app-54d1e.firebasestorage.app',
    iosClientId: '331400873826-60c37u1d44338jtiomiv4ls6ep4eglji.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASa2g3kae3Jezy0wlsC25Ggx66GN-rWws',
    appId: '1:331400873826:web:04f4c473f2b5c349850e3b',
    messagingSenderId: '331400873826',
    projectId: 'ecommerce-app-54d1e',
    authDomain: 'ecommerce-app-54d1e.firebaseapp.com',
    storageBucket: 'ecommerce-app-54d1e.firebasestorage.app',
  );
}
